spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://comvisitor.cvysc3moexiz.ap-southeast-1.rds.amazonaws.com/goodluck_db
    username: root
    password: comvisitor1234
    hikari:
      maximum-pool-size: 5
      connection-timeout: 180000
  jpa:
    hibernate.ddl-auto: none
    hibernate.use-new-id-generator-mappings: false
  jackson.time-zone: Asia/Bangkok